url: https://y7kim.github.io

# Site settings
title: Club Cedille
email: clubcedille@gmail.com
description: "Club Cedille Description"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Riku Avelar
  pic: riku
  position: Javascript Pilgrim
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
