url: http://cedille.etsmtl.ca

# Site settings
title: Club CEDILLE
email: cedille@etsmtl.net
description: "Club CEDILLE: Club de DevOps et de logiciels libres situé à l'École de Technologie Supérieure"
image: "/img/logos/cedille-logo-new.png"

photoAttribution:
  title: Photo
  author: Arkadiusz Sikorski
  photoLink: https://www.flickr.com/photos/arakus/8077218145/
  license: CC BY 2.0
  licenseLink: https://creativecommons.org/licenses/by/2.0/

# Resource types
collections:
  # - posts
  - projects
  - sites

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fec503
  secondary: ee9911
  secondary-dark: '000'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  facebook:
    title: facebook
    url: http://facebook.com/clubcedille
  github:
    title: github
    url: http://github.com/ClubCedille
  linkedin:
    title: linkedin
    url: https://www.linkedin.com/company/cedille

defaults:
  -
    scope:
      path: "" # All files
    values:
      lang: fr

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - .travis.yml
  - vendor
